### ISSUE TITLE
[Help] 在windows上nslookup不显示服务器名称了

### ISSUE THREAD

**Issue by VwEl** [kkkgo/PaoPaoDNS#136]
### 在提交之前，请确认

- [X] 我已经尝试执行test.sh并搜索过Issue和discussions和文档，但没有找到相关问题。
- [X] 我正在使用最新的docker镜像版本（可以尝试`docker pull sliamb/paopaodns:latest`后重新创建容器）。

### 脚本自检日志

```txt
images build time : 2024-05-03 06:13:39 UTC
check for the latest version ,
go to https://github.com/kkkgo/PaoPaoDNS/discussions 
-> test start `1714767909`

[INFO] ALL TEST PASS.✅

-> test end `1714767913`
```

### 问题描述和复现步骤

一个月前搭建配置完都挺正常，今天心血来潮试了一下发现  服务器:变成UnKnown，经过测试其余功能倒是挺正常。就是想搞明白为啥名称会不显示了

**Comment by kkkgo** [comment]
https://github.com/kkkgo/PaoPaoDNS/blob/008fa7d559bad3854e08b4ae2a05a20302dba0e8/README.md?plain=1#L115-L116

显示名称的原理是提供服务器IP的反向记录，只有容器IP和提供服务IP一致的时候才能显示，也就是host或者macvlan等独立IP网络模式，或者指定SERVER_IP参数。

**Comment by VwEl** [comment]
> https://github.com/kkkgo/PaoPaoDNS/blob/008fa7d559bad3854e08b4ae2a05a20302dba0e8/README.md?plain=1#L115-L116
> 
> 显示名称的原理是提供服务器IP的反向记录，只有容器IP和提供服务IP一致的时候才能显示，也就是host或者macvlan等独立IP网络模式，或者指定SERVER_IP参数。
是host 模式配置的，刚配置完是正常显示PaoPaoDNS，是突然变成UnKnown的
蛮怪的

**Comment by kkkgo** [comment]
配置一下SERVER_IP参数为你查询的DNS的IP。

**Comment by kkkgo** [comment]
刚配置完是正常显示PaoPaoDNS，是突然变成UnKnown的
鉴于你配置的是host模式，可以留意一下是否和宿主机有端口占用冲突。
