### ISSUE TITLE
[Help] 使用群晖的DOCKER拉取镜像创建后没有REDIS缓存文件？

### ISSUE THREAD

**Issue by cococle** [kkkgo/PaoPaoDNS#203]
### 在提交之前，请确认

- [X] 我已经尝试执行test.sh并搜索过Issue和discussions和文档，但没有找到相关问题。
- [X] 我正在使用最新的docker镜像版本（可以尝试`docker pull sliamb/paopaodns:latest`后重新创建容器）。

### test.sh脚本自检日志

```txt
使用群晖的DOCKER拉取镜像创建后没有REDIS缓存文件？
```

### debug.sh脚本自检日志

```txt
使用群晖的DOCKER拉取镜像创建后没有REDIS缓存文件？
```

### 问题描述和复现步骤

创建后没有REDIS缓存文件？

**Comment by kkkgo** [comment]
https://github.com/kkkgo/PaoPaoDNS/issues/1
