### ISSUE TITLE
[Help] 请问默认它是使用哪些上级dns来查询的？

### ISSUE THREAD

**Issue by cococle** [kkkgo/PaoPaoDNS#205]
### 在提交之前，请确认

- [X] 我已经尝试执行test.sh并搜索过Issue和discussions和文档，但没有找到相关问题。
- [X] 我正在使用最新的docker镜像版本（可以尝试`docker pull sliamb/paopaodns:latest`后重新创建容器）。

### test.sh脚本自检日志

```txt
请问默认它是使用哪些上级dns来查询的？
```

### debug.sh脚本自检日志

```txt
请问默认它是使用哪些上级dns来查询的？
```

### 问题描述和复现步骤

默认它是使用哪些上级dns来查询的？

**Comment by kkkgo** [comment]
https://blog.03k.org/post/paopaodns.html
