### ISSUE TITLE
[Help] 断流问题后续

### ISSUE THREAD

**Issue by cococle** [kkkgo/PaoPaoDNS#213]
### 在提交之前，请确认

- [X] 我已经尝试执行test.sh并搜索过Issue和discussions和文档，但没有找到相关问题。
- [X] 我正在使用最新的docker镜像版本（可以尝试`docker pull sliamb/paopaodns:latest`后重新创建容器）。

### test.sh脚本自检日志

```txt
没有日志提供
```

### debug.sh脚本自检日志

```txt
主路由是爱快，如果是不勾选DNS劫持到PAOPAODNS，就会出现断流，劫持了后就一切正常了。
```

### 问题描述和复现步骤

主路由是爱快，如果是不勾选DNS劫持到PAOPAODNS，就会出现断流，劫持了后就一切正常了。

**Comment by cococle** [comment]
静态路由，NAT这些都在爱快添加的了。

**Comment by cococle** [comment]
以及存在第二种解决方式，不知道爱快是怎么处理首选和备选DNS的顺序，如果首选是paopaodns的IP,备选是223.5.5.5，没有在爱快劫持DNS到paopaodns所在的IP时候，就会出现断流，如果首选和备选都是内网两个paopaodns所在的IP,那么就不会出现断流，

爱快不劫持DNS的情况下结论是：
首选DNS是paopaodns的IP,备选是223.5.5.5  ，断流，中间可能用到了223.5.5.5这个IP去解析
首选和备选都是内网两个paopaodns所在的IP,不断流.

**Comment by kkkgo** [comment]
理解错误，备用dns的行为取决于客户端。
参考https://github.com/kkkgo/PaoPaoGateWay/discussions/39#discussioncomment-7664788

**Comment by cococle** [comment]
所以客户端随机DNS的话，翻墙就容易出现断流了呀？

**Comment by kkkgo** [comment]
所以问题在于你为啥要给客户端分配不能分流的“随机DNS”？

**Comment by cococle** [comment]
是滴，如果分配了阿里等国内其他dns，绝对会出现断流。
