### ISSUE TITLE
大佬，你好，有问题请教一下，谢谢

### ISSUE THREAD

**Issue by snakwu** [kkkgo/PaoPaoDNS#234]
paopao dns只能作一个单纯的上游dns吗，可以和passwall配合国内外dns分流吗，另外这个可以配合去广告规则，达到去广告功能吗，谢谢🙏

**Comment by kkkgo** [comment]
1、paopaodns本身就有分流功能
2、https://github.com/kkkgo/PaoPaoDNS/discussions/77

**Comment by snakwu** [comment]
> 1、paopaodns本身就有分流功能 2、#77

谢谢回复，大概明白了
1,国内外分流，就是把CNAUTO打开
2.要去广告，就把paopao dns作为adghome的上游
应该是这样吧
