### ISSUE TITLE
大佬，你好，关于SOCKS5问题请教下

### ISSUE THREAD

**Issue by snakwu** [kkkgo/PaoPaoDNS#235]
大佬你好，请问你如果我设置参数SOCKS5=@10.10.10.8:1070，强制使用代理后，如果SOCKS5服务器不可用了，dnscrypt会不会回退查询，谢谢！

**Comment by kkkgo** [comment]
不会

**Comment by snakwu** [comment]
> 不会

大佬，可否加个回退功能，检测到代理服务器不通，就回退🥴，谢谢

**Comment by kkkgo** [comment]
你不强制就会回退。

**Comment by snakwu** [comment]
明白，谢谢

**Comment by snakwu** [comment]
> 你不强制就会回退。

大佬，关于redis_dns_v2.rdb固化缓存，随着时间的推移，会不会同一个域名使用新的解释复盖redis_dns_v2.rdb里面的旧条目？谢谢
